config/routes.rb
Rails.application.routes.draw do
  resources :champions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/champion.rb
class Champion < ApplicationRecord
    has_many :skins
    validates :name, uniqueness: true
end

app/models/skin.rb
class Skin < ApplicationRecord
    belongs_to :champion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  def index
    @champions = Champion.order (:name)
  end
  def new
    @champion = Champion.new
  end
  def create
    @champion = Champion.new(champion_params)
    if @champion.save
      redirect_to champions_path
    else
      render :new
    end
  end
  private def champion_params
    params.require(:champion).permit(:name, :owned, :rp_cost, :be_cost)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champion_helper.rb
module ChampionHelper
end

app/views/champions/index.html.erb
<h1>Champion</h1>

<table>
  <tr>
    <th>name</th>
    <th>owned</th>
    <th>rp_cost</th>
    <th>be_cost</th>
    <th>skins</th>
  </tr>
  <% @champions.each { |ch| %>
  <tr>
    <td> <%= ch.name %> </td>
    <td> <%= ch.owned %> </td>
    <td> <%= ch.rp_cost.round %> </td>
    <td> <%= ch.be_cost.round %> </td>
    <td> <ul> <% ch.skins.each { |sk| %>
          <li> <%= sk.name %> </li>
          <% } %> </ul> </td>
  </tr>
<%}%>
</table>

<%= link_to "Add champion", new_champion_path %>

app/views/champions/new.html.erb
<h1> Insert Champion </h1>

<%=form_for(@champion) do |ff| %>

Name: <%= ff.text_field :name %> <br />

Owned: <%= ff.check_box :owned %> <br />

Rp_cost: <%= ff.text_field :rp_cost %> <br />

Be_cost: <%= ff.text_field :be_cost %> <br />

<%= ff.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeagueStuff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>